version: 2

python:
  version: 3.6

# You can include or exclude git submodules from the Read the Docs
# documentation build.
# https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules
submodules:
  include: all
